- qstat.cfg
Hi, three fixes from the [XQF](https://github.com/XQF/xqf/) project:
* fix warsow qstat.cfg breaking getting servers for any game. The issue is apparently that Q2S doesn't have status2 packet. So use Q3S, which some other id tech 2 games already use (such as Nexuiz).
https://github.com/XQF/xqf/commit/ee2a392f150251b33a1ebda5cf2874290feaa181 by @zturtleman
* use dpmaster gamename when requesting servers for q3rally
https://github.com/XQF/xqf/commit/ce32b3608a912bb78d1b6faafc62504effdf62e8 by @zturtleman
* allow xqf/qstat to query empties and full wolfet/etlegacy servers
https://github.com/XQF/xqf/commit/f63633570f8ca17763ff430e851e592e1794289b by @illwieckz
> fix etlegacy/wolfet, warsow and q3rally server query

- qstat.c
Hi, the `for` test now checks if `i < n_server_types`, even if `Q_UNKNOWN_TYPE` is always the last gametype.
* fix the issue #21, needed by PR #13 .
This issue is more than 13 years old, but since  `Q_UNKNOWN_TYPE` is always the last gametype, no problem has never occured.
> iterator limit now match malloc in protocol listing, fix #21, ref #13

- xform.c
Hi, this PR fixes the ut2004 color transformation overflow, as reported in #11.
It's mergeable on master.
> fix the ut2004 color transformation overflow, fix #11

- qstat.cfg
OpenArena 0.8.5 changed its protocol version to 71 which makes current QStat default config dysfunctional. This PR fixes it.
> Config: bump default OpenArena protocol version

- a2s.c
Fix a2s player query again which has been broken by source updates again.
We again use the alternative method of requesting players with an invalid challenge.
This fixes #46.
> Fix a2s player query

- qstat.h
- tee.c
- tee.h
Hi, this fixes the Teeworlds server query, it tries with the 3 known `getinfo` packets.
I renamed the `-tee` argument to `-tees` since I will work next on the `-teem` Teeworlds master query.
Since Teeworlds support was broken since many years, there is probably nobody that uses the `-tee` arg today.
> Fix Teeworlds server query, #3

- tee.c
Fix the use of uninitialised skip variable in tee.
> Fix uninitialised warning in tee

- qstat.c
- document nx/nnx options
- have a nice usage aligned print
- organized options
- use qstat standard option format for JSON protocol and version query
- add qstat standard option format for help query
- add standard version query
> enhance the qstat help and query, fix #17

- qstat.h
- tee.c
- tee.h
Hi, this change adds [TeeWorlds](https://www.teeworlds.com/) master server to Qstat, the [two known list formats](https://github.com/teeworlds/teeworlds/blob/master/scripts/tw_api.py#L18) are supported.
You can test it these ways:
```
qstat -teem master2.teeworlds.com:8300
qstat -json -teem master2.teeworlds.com:8300
```
For reference, this will close #5 and is needed by XQF/xqf#82.
> add teeworlds master query, fix #5

- display_json.c
- qstat.c
- qstat.h
- tf.c
Update tf to support v3 / v4 protocol.
If a key is specified v4 protocol is used otherwise v3 protocol is used for compatiblity as v4 is not fully deployed.
This also refactors the way details are read making use of common pkt_XXX methods which validate the packet is valid for the given request.
Also:
* Enable json output of player and rule information for tf.
> Update tf to support v4 protocol

- ts3.c
Corrected the parameter order for teamspeak 3 login command for single server requests which was inverted.
> Fixed ts3 login parameter order

- Makefile.noauto
- qstat.h
- tf.c
Fixed titanfall incorrect handling of integer types.
Also:
* Fixed compilation under titanfall compilation under VC++
* Fixed compilation under later versions of VC++ which define snprintf and not just _snprintf.
* Added removal of VC++ *.pdb files in clean target of noauto.
> Fixed titanfall protocol handling of ints

- display_json.c
The return type `-json` flag did not return the same results as `-raw`.
The JSON return type was missing a teams object.
> [Tribes 2] Return teams as an object

- a2s.c
Although not technically needed for servers using the valve SDK, use a challenge of -1 (0xFFFFFFFF) instead of 0 to trigger a challenge response as that's whats documented:
https://developer.valvesoftware.com/wiki/Server_queries#Request_Format_5
This improves compatibility with 3rd party implementations of the a2s protocol.
> Always use challenge -1 to trigger a challenge response

- tf.c
Fixed windows build to use of bzero which isn't present, instead use memset.
> Fixed windows build due to bzero

- utils.h
Hi,
This is just a rework of a previous PR I closed. OpenBSD does not have strnstr(), so I've removed it from utils.h if defined().
Thanks,
Tom
> OpenBSD does not have strnstr(), only FreeBSD does.

- qstat.c
- qstat.cfg
Quetoo, formerly known as Quake2World, is Quake 2 based multiplayer game. See [quetoo.org](http://quetoo.org/).
> add Quetoo support

- qstat.cfg
TremFusion was a project aimed to improve the tremulous client,
the TremFusion is dead since years and people who still use their
binaries (either as client or server) today just use it as
alternative binaries for the same game, using the same protocol
and same ports etc. There is no reason to keep two entries that
does the same thing. We can see TremFusion as an alternative build
of the same Tremulous game. And since the project is dead and six
feets under, this will never change.
The -tremulouss and -tremulousm options do the thing very well.
> remove tremfusion (tremulous does the thing)

- .travis.yml
- qstat.cfg
It looks like I hit a sneaky merge issue while rebasing #75 on master…
I updated Travis config file to make it test the validity of `qstat.cfg` after having successfully built `qstat`.
> fix sneaky mistake in qstat.cfg, make travis check for its validity

- qstat.cfg
- tf.c
In order to ensure the new Titanfall 2 protocol v2 is backwards compatible, use the full status packet definition from qstat.cfg.
> Made Titanfall 2 protocol v2 backwards compatible

- .gitignore
We don't want windows build files committed so add them to .gitignore.
> Added .obj and .pdb files to .gitignore

- tf.c
Fixed the offset used for the titanfall custom packet type check.
> Fixed offset of titanfall custom packet type check

- debug.c
- debug.h
- display_json.h
On gcc-10 (and gcc-9 -fno-common) build fails as:
```
gcc ... -o qstat ...
ld: config.o:qstat/display_json.h:24:
multiple definition of `json_printed'; xform.o:qstat/display_json.h:24: first defined here
ld: config.o:qstat/display_json.h:23:
multiple definition of `json_encoding'; xform.o:qstat/display_json.h:23: first defined here
```
gcc-10 will change the default from -fcommon to fno-common:
https://gcc.gnu.org/PR85678.
The error also happens if CFLAGS=-fno-common passed explicitly.
Reported-by: Toralf Förster
Bug: https://bugs.gentoo.org/706390
> qstat: fix build failure against gcc-10

- qstat.h
This enables query arg params to be parsed from host file as well as directly on the command line.
> feat: Enable tf query args

- ut2004.c
Fix the file detection method used by ut2004 to support Windows paths as well as Unix paths.
Fixes #96
> fix(ut2004): cdkey file detection on Windows

- a2s.c
Add support for the reflection mitigation support detailed here:
https://steamcommunity.com/discussions/forum/14/2974028351344359625/
This allows A2S_INFO to return A2S_CHALLENGERESPONSE which requires retrying the A2S_INFO request with the specified challenge.
If deal_with_a2s_packet calls send_a2s_rule_request_packet it now returns this value directly as it already has the right return value.
Also:
* Cleanup return processing.
* Add some additional debug.
Fixes #107
> feat(a2c): Reflection mitigation support

- qstat.c
Fix q2 parsing for Xonotic with gametype CA which has a leading float for damage not int for frags.
Fixes #89
> fix(q2): Xonotic with gametype CA

- qserver.c
- qserver.h
- qstat.c
Fix Hexen 2 player details by enabling next_player_info flow.
Also:
* Extract code send code into send_packet_raw and use in all send methods. This enables easy conversion of callers using send(...)  to use a version which supports packet debugging.
> fix(hexen2): player details
